### ISSUE TITLE
Disable `eslint-config-prettier/@typescript-eslint` per Prettier upstream changes

### ISSUE THREAD

**Issue by poteat** [davidjbradshaw/eslint-config-adjunct#49]
See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21

On a higher level, it'd be nice if we could configure the set of permissible packages installed by adjunct via some kind of blacklist system.

**Comment by davidjbradshaw** [comment]
This was fixed in v4.10

how do you think the permissible thing would work?

sorry for the slow reply, had a bike crash and have been recovering for the last four weeks
