### ISSUE TITLE
npm-check-updates dep.

### ISSUE THREAD

**Issue by brettz9** [davidjbradshaw/eslint-config-adjunct#6]
Hi,

Thanks for the helpful collection!

I don't think you want `npm-check-updates` as a dep. here... Even as a devDep it seems unusual...

**Comment by davidjbradshaw** [comment]
It's currently used by the prepublish script to check everything is up to date

**Comment by brettz9** [comment]
I don't see it referenced in `package.json` except as a dependency... And as a prepublish script, it should only need to be a devDependency if you really want it local...
